Desktop/eazycoin/wallet/urls.py
from argparse import Namespace
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'wallet'

urlpatterns = [
    path('', views.mywallet, name='mywallet'),
    path('services/', views.services, name= 'services'),
    path('withdraw/', views.withdraw, name='withdraw'),
    
   # path('pics/download_2.jpeg', views.viewpayment)
]

Desktop/eazycoin/wallet/models.py
from email.policy import default
from typing_extensions import Required
from django.db import models
from django.utils import timezone
from django.forms import DateTimeField
import datetime
from PIL import Image
from django.contrib.auth.models import User

# Create your models here.
class PaymentProve(models.Model):
    
    username = models.CharField(max_length=50)
    amount = models.IntegerField()
    image = models.ImageField(default='img')
    date_posted = models.DateTimeField(auto_now_add=datetime.datetime.now())
    checked = models.BooleanField(default=False) 

    def save(self):
        super().save()
        return PaymentProve
    def __str__(self):
        return f'{self.username} paymentprove'
    
    # def img(self):
    #     image = Image.image
    #     return image
        

Desktop/eazycoin/wallet/forms.py
from cProfile import label
from dataclasses import field, fields
from email.policy import default
from django.shortcuts import render, redirect
from pyexpat import model
from pyexpat.errors import messages
from re import template
from urllib import request
from django.utils import timezone
from django.contrib.auth.models import User
from django import forms
from .models import PaymentProve

class PaymentForm(forms.ModelForm):
    # username = forms.CharField(max_length=255)
    # amount = forms.IntegerField()
    # image = forms.ImageField()
    class Meta:
        model = PaymentProve
        fields = ['username', 'amount', 'image']

Desktop/eazycoin/wallet/views.py
from email import message
import mailbox
from eazycoin import settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.http import HttpResponse
from django.template import loader
from .forms import PaymentForm
from django.contrib import admin
from .models import PaymentProve
from django.core.mail import send_mail, mail_admins


# Create your views here.
# @login_required
# def viewpayment(request):
#     if request.user.is_superuser:
#         return render(request, 'wallet/pics')
@login_required    
def mywallet(request):
    if request.method == 'POST':
        p_form =PaymentForm(request.POST)
        if p_form.is_valid():
            obj = p_form.save(commit=False)
            obj.save()
            messages.success(request, 'your payment prove has been submitted successfully')
            mail_admins(
                'A new paymentprove has been submitted by {user.username}',
                'you received a new application. Please check it out in the administration console details are as follows',
                'from {user.email}',
            )
        else:
            messages.info(request, 'not submitted')
        
    else:
        p_form = PaymentForm()
    return render(request, 'wallet/mywallet.html', {'form':p_form})

def services(request):
        return render(request, 'wallet/services.html')
    
    
def withdraw(request):
    return render(request, 'wallet/withdraw.html')
    

    
    

Desktop/eazycoin/wallet/templates/wallet/mywallet.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>EZ WALLET</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'wallet/css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" href="{% static 'wallet/css/style.css' %}">
    <!-- responsive-->
    <link rel="stylesheet" href="{% static 'wallet/css/responsive.css' %}">
    <!-- awesome fontfamily -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="{% static 'wallet/images/loading.gif' %}" alt="img" /></div>
    </div>
    <!-- end loader -->
    <div id="mySidepanel" class="sidepanel">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
        <a  href="{% url 'index' %}">Home</a>
        <a href="{% url 'about' %}">About</a>
        <a href="{% url 'wallet:services' %}">What We do</a>
        <a href="" class="active">wallet</a>
        <a href="#contact">Contact</a>
     
        <a href="{% url 'wallet:mywallet' %}">Invest</a>
        <a href="{% url 'wallet:withdraw' %}">Withdraw</a>
        <a href="#">Logout</a>
    </div>
    <!-- header -->
    <header>
        <!-- header inner -->
        <div class="head-top">
            <div class="container-fluid">
                <div class="row d_flex">
                    <div class="col-sm-3">
                        <div class="logo">
                            <a href="{% url 'index' %}">EZXICOIN</a>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <ul class="social_icon text_align_right d_none">
                            <li> <a href="Javascript:void(0)"><i class="fa fa-facebook-f"></i></a></li>
                            <li> <a href="Javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                            <li> <a href="Javascript:void(0)"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                            <li> <a href="Javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            <li> <a href="Javascript:void(0)"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                    <div class="col-sm-4">
                        <ul class="email text_align_right">
                            <li class="d_none"><a href="{% url 'profile' %}"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                            <li class="d_none"> <a href="Javascript:void(0)"><i class="fa fa-search" style="cursor: pointer;" aria-hidden="true"></i></a> </li>
                            <li>
                                <button class="openbtn" onclick="openNav()"><img src="{% static 'accounts/images/menu_btn.png' %}"></button>
                            </li>
                        </ul>
                    </div>
                </div>
            </d
        </div>
    </header>
    <!-- end header -->
    <!-- testimonial -->
    {% block content %}
    <h2>{{user.username|capfirst}}'s wallet</h2>
   {% endblock %}
    <div class="testimonial">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="border_testi">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="titlepage text_align_center">
                                    <h2>WALLET</h2>
                                </div>
                            </div>
                        </div>
                        <div class="row d_flex">
                            <div class="col-md-10 offset-md-1">
                                <div id="testimo" class="carousel slide our_testimonial" data-ride="carousel">
                                    
                                    <div class="carousel-inner">
                                        <div class="carousel-item active">
                                            <div class="container">
                                                <div class="carousel-caption posi_in">
                                                    <div class="row">
                                                        <div class="col-md-3">
                                                            <div class="testomoniam_text text_align_center">
                                                               
                                                               
                                                            </div>
                                                        </div>
                                                        <div class="col-md-9">
                                                            <div class="testomoniam_text text_align_left">
                                                                
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    
                                       
                                    <a class="carousel-control-prev" href="#testimo" role="button" data-slide="prev">
                                        <i class="fa fa-angle-left" aria-hidden="true"></i>
                                        
                                    </a>
                                    <a class="carousel-control-next" href="#testimo" role="button" data-slide="next">
                                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                                      
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer -->
    <footer>
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <a class="logo_bottom" href="{% url 'index' %}">EZXICOIN</a>
                    </div>
                    <div class="col-md-3 col-sm-6" ">
                  <div class="Informa conta ">
                     <h3>Contact Us</h3>
                     <ul>
                        <li> <a href="Javascript:void(0) "> <i class="fa fa-map-marker " aria-hidden="true "></i> Abuja Nigeria
                           </a>
                        </li>
                        <li> <a href="Javascript:void(0) "><i class="fa fa-phone " aria-hidden="true "></i> +44 7448 325625
                           </a>
                        </li>
                        <li> <a href="Javascript:void(0) "> <i class="fa fa-envelope " aria-hidden="true "></i> info@ezxicoin.com
                           </a>
                        </li>
                     </ul>
                  
                  </div>
               </div>
               <div class="col-md-3 col-sm-6 "">
                        <div class="Informa helpful">
                            <h3>Useful Link</h3>
                            <ul>
                                <li><a href="">INVEST</a>
                                </li>
                                <li><a href="{% url 'wallet:withdraw' %}">WITHDRAW</a>
                                </li>
                                <li><a href="">WALLET</a>
                                </li>
                                <li><a href="{% url 'contact' %}">CONTACT</a>
                                </li>
                                <li><a href="#">ABOUT</a>
                                </li>
                                <li><a href="#">WHAT WE DO</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6" ">
                  <div class="Informa ">
                     <h3>Offices</h3>
                     <ul>
                        <li>T12 Alibro Atrium, 33 A.E.                            
                        </li>
                        <li>Ekukinam St, Utako                      
                        </li>
                        <li>Abuja, FCT 900001                       
                        </li>
                        <li>Nigeria                           
                        </li>

                     </ul>
                  </div>
               </div>
               <div class="col-md-3 col-sm-6 ">
                  <div class="Informa ">
                     <h3>Newsletter</h3>
                     <form class="newslatter_form " method="POST">
                        {% csrf_token %}
                        <input class="ente " placeholder="Enter your email " type="text " name="Enter your email ">
                        <button class="subs_btn ">Subscribe</button>
                     </form>
                  </div>
               </div>
            </div>
            <div class="copyright text_align_center ">
               <div class="container ">
                  <div class="row ">
                     <div class="col-md-12 ">
                        <p>Copyright &copy 2022 EZ Coin. All Rights Reserved.</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </footer>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="{% static 'wallet/js/jquery.min.js ' %}"></script>
      <script src="{% static 'wallet/js/bootstrap.bundle.min.js' %} "></script>
      <script src="{% static 'wallet/js/jquery-3.0.0.min.js ' %}"></script>
      <script src="{% static 'wallet/js/custom.js ' %}"></script>
   </body>
</html>

Desktop/eazycoin/wallet/templates/wallet/services.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>EZ SERVICES</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'wallet/css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" href="{% static 'wallet/css/style.css' %}">
    <!-- responsive-->
    <link rel="stylesheet" href="{% static 'wallet/css/responsive.css' %}">
    <!-- awesome fontfamily -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="{% static 'wallet/images/loading.gif' %}" alt="" /></div>
    </div>
    <!-- end loader -->
    <div id="mySidepanel" class="sidepanel">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
        <a href="{% url 'dashboard' %}">Home</a>
        <a href="{% url 'about' %}">About</a>
        <a href="" class="active">What We do</a>
        <a href="{% url 'wallet:mywallet' %}">wallet</a>
        <a href="{% url 'contact' %}">Contact</a>
       
        <a href="{% url 'wallet:mywallet' %}">Invest</a>
        <a href="{% url 'wallet:withdraw' %}">Withdraw</a>
        <a href="">Logout</a>
    </div>
    <!-- header -->
    <header>
        <!-- header inner -->
        <div class="head-top">
            <div class="container-fluid">
                <div class="row d_flex">
                    <div class="col-sm-3">
                        <div class="logo">
                            <a href="">EZXICOIN</a>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <ul class="social_icon text_align_right d_none">
                            <li> <a href="Javascript:void(0)"><i class="fa fa-facebook-f"></i></a></li>
                            <li> <a href="Javascript:void(0)"><i class="fa fa-twitter"></i></a></li>
                            <li> <a href="Javascript:void(0)"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                            <li> <a href="Javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            <li> <a href="Javascript:void(0)"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                    <div class="col-sm-4">
                        <ul class="email text_align_right">
                            <li class="d_none"><a href="{% url 'profile' %}"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                            <li class="d_none"> <a href="Javascript:void(0)"><i class="fa fa-search" style="cursor: pointer;" aria-hidden="true"></i></a> </li>
                            <li>
                                <button class="openbtn" onclick="openNav()"><img src="{% static 'wallet/images/menu_btn.png' %}"></button>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- end header -->

    <!-- wallet -->
    <div id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="about_border">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="titlepage text_align_left">
                                    <h2>WHAT WE DO</h2>
                                </div>
                                <div class="about_text">
                                   <p>
                                    Exportation of Commodities from Nigeria to the UK and the rest of the world. <br>
Our exportation subsidiary – EZ Xport Investment Limited is duly registered in Nigeria with the Corporate Affairs Commission as well as with the Nigerian Export Promotion Council to carry out the business of production, distribution, sales and exportation of agricultural products. We export containers, on large scale.
<br>
By investing your EZ Coin wallet, you are also investing your token in exportation of commodities like Palm Oil, Charcoal, Dried Fish, etc. You may find details on our website – https://ezxportinvestment.com.
<br>
<p>Foreign Exchange <br>
    We are into physical buying and selling of currency pairs. <br>
    Everyday, currency pairs are being traded to meet up with demand for international transactions. We are active players in this domain with guarantee of profits.
    </p>
<p>Hospitality <br>
    We have hotel and serviced apartments in Nigeria and the UK. By investing your EZ Coin Wallet, you are also investing into our hospitality business with promised return on investment guaranteed. <br>

    Visit https://ez-hospitality.com for more about our hospitality business.</p>


                                   </p>
                                  
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="about_img">
                                    <figure><img class="img_responsive" src="{% static 'wallet/images/ezcoin-logo1.png' %}" alt="#" /></figure>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer -->
    <footer>
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <a class="logo_bottom" href="">EZXICOIN</a>
                    </div>
                    <div class="col-md-3 col-sm-6" ">
                  <div class="Informa conta ">
                     <h3>Contact Us</h3>
                     <ul>
                        <li> <a href="Javascript:void(0) "> <i class="fa fa-map-marker " aria-hidden="true "></i> Abuja Nigeria
                           </a>
                        </li>
                        <li> <a href="Javascript:void(0) "><i class="fa fa-phone " aria-hidden="true "></i> +44 7448 325625
                           </a>
                        </li>
                        <li> <a href="Javascript:void(0) "> <i class="fa fa-envelope " aria-hidden="true "></i> info@ezxicoin.com
                           </a>
                        </li>
                     </ul>
                  
                  </div>
               </div>
               <div class="col-md-3 col-sm-6 "">
                        <div class="Informa helpful">
                            <h3>Useful Link</h3>
                            <ul>
                                <li><a href="{% url 'wallet:mywallet' %}">INVEST</a>
                                </li>
                                <li><a href="{% url 'wallet:withdraw' %}">WITHDRAW</a>
                                </li>
                                <li><a href="{% url 'wallet:mywallet' %}">WALLET</a>
                                </li>
                                <li><a href="{% url 'contact' %}">CONTACT</a>
                                </li>
                                <li><a href="{% url 'about' %}">ABOUT</a>
                                </li>
                                <li><a href="{% url 'wallet:services' %}">WHAT WE DO</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6" ">
                  <div class="Informa ">
                     <h3>Offices</h3>
                     <ul>
                        <li>T12 Alibro Atrium, 33 A.E.                            
                        </li>
                        <li>Ekukinam St, Utako                      
                        </li>
                        <li>Abuja, FCT 900001                       
                        </li>
                        <li>Nigeria                           
                        </li>

                     </ul>
                  </div>
               </div>
               <div class="col-md-3 col-sm-6 ">
                  <div class="Informa ">
                     <h3>Newsletter</h3>
                     <form class="newslatter_form " method="POST">
                        {% csrf_token %}
                        <input class="ente " placeholder="Enter your email " type="text " name="Enter your email ">
                        <button class="subs_btn ">Subscribe</button>
                     </form>
                  </div>
               </div>
            </div>
            <div class="copyright text_align_center ">
               <div class="container ">
                  <div class="row ">
                     <div class="col-md-12 ">
                        <p>Copyright © 2022 EZ Coin. All Rights Reserved.</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </footer>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="{% static 'wallet/js/jquery.min.js' %}"></script>
      <script src="{% static 'wallet/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'wallet/js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'wallet/js/custom.js' %}"></script>
   </body>
</html>

Desktop/eazycoin/wallet/templates/wallet/this/mywallet.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <script src = "{% static 'wallet/script.js' %}"></script> 
        <link rel="stylesheet" href="{% static 'wallet/mywallet.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
        <link href='https://fonts.googleapis.com/css?family=Akaya Telivigala' rel='stylesheet'>
    </head>
    <body >
    <div class="navcont">
          <img class="img" src="{% static 'accounts/ezcoin-logo1.png' %}" alt="My image" class="logo">
          <ul class="top">
            <li><a href="{% url 'dashboard' %}">HOME</a></li>
                <li><a href="{% url 'index' %}">ABOUT</a></li>
                    <li><a href="{% url 'index' %}">WHAT WE DO</a></li>
                        <li><a href="#social" id="contactnav">CONTACT</a></li>
          </ul>
        </div>
    </div>
        <div class="head">
        <h2>{{user.username|capfirst}}'s wallet</h2>
    </div>
    <div class="bal">
        <label for="balance">wallet balance</label>
        <p>{{accounts.profile.amount}}</p>
        </div>
<div class="container" id ="container">

    {% if messages %}
{% for message in messages %}
<div style="width:100%; font: 1.5em itallic">{{ message}}</div>
{% endfor %}
{% endif %}
    <div class="card1">
<button onclick="myfunction()">pay into wallet</button>


<div id="SubmitPayment">
 
    <form class="formEl" method="POST" id="formEl" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type= "text" name="username" placeholder="enter your username">
        <label for="amount">Amount</label>
        <input type="tel" name="amount" id="surname" placeholder="enter the amount paid"><br>
        <label for="img">UploadPaymentSlip</label>

        <input type="file" name="img" id="img" value="upload your image here">
                 <input id="submit" type="submit" value="submit">
    </form>
 
</div>
</div>
</div>
<div class="footer">
    <div class="contact">contact us  here</div>
    <div class="social" id="social">
        <ul class="bottom">
            <li>Email</li>
            <li>Whatsapp</li>
            <li>Facebook</li>
            <li>Instagram</li>
            <li>discord<li>
        </ul>
    </div>
    <div class="copyright"><p>&copy superman 2022</p></div>
    

</div>
    </body>
    </html>

Desktop/eazycoin/wallet/templates/wallet/this/withraw.html
<html>
<head>
<title>EZ COIN</title>
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="HandheldFriendly" content="true">
</head>
<style>
body{
background-color:darkblue;
}
.logo{
width:100px;
}
li a{
color:white;
}
.form{
width:100%;
display:flex;
align-items:center;
text-align:center;
justify-content:center;
}
.form form{
background:white;
width:70%;
padding:2em;
}
ul{
list-style-type:none;
float:right;
color:blue;
}
li{
display:inline;
padding:2px;
margin:6px;

}
li a{
text-decoration:none;
}
body {
  margin: 0;
  padding: 0;
}
.logo {
  float: left;
}
.navigation-bar {

margin: 0 auto;
height: px;
}

#navigation-container{
height: px;
width: 100%;
}

#navigation-container ul {
padding: 0px;
margin: 0px;
text-align: center;
}

#navigation-container li {
list-style-type: none;
padding: 0px;
height: 24px;
margin-top: 4px;
margin-bottom: 4px;
display: inline;
}

#navigation-container li a {
font-size: 16px;
font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
text-decoration: none;
line-height: 70px;
padding: 5px 15px;
opacity: 0.7;
}
html{
    font-size: small;
}
#menu {
float: right;
}
footer {    
left: 10px;  
bottom: 5px;  
right: 10px;   
width: 95%;  
background-color:deep-blue;  
color: white;  
text-align: center;  
}  
@media screen and (max-width: 460px) {
#navigation-container a:not(:first-child) {display: none;}
#navigation-container a.icon {
  float: right;
  display: block;
}
}
@media screen and (max-width: 460px) {
#navigation-container.responsive {position: relative;}
#navigation-container.responsive a.icon {
 margin: left 10px;
  right: 0;
  top: 0;
}
#navigation-container.responsive a {
  float: none;
  display: block;
  text-align: left;
}
}
@media screen and (max-width: 460px) {
#navigation-container.responsive {position: relative;}
#navigation-container.responsive a.icon {
 margin: left 10px;
  right: 0;
  top: 0;
}
#navigation-container.responsive a {
  float: none;
  display: block;
  text-align: left;
}
}

@media screen and (max-width: 225px) {
  .navigation-bar.responsive {position: relative;}
  .navigation-bar.responsive a.icon {
    position: absolute;
    right: 0;
    top: 0;
  }

  .navigation-bar.responsive a {
    float: none;
    display: block;
    text-align: left;
  }
}
@media screen and (max-width: 225px) {
  .topnav a:not(:first-child) {display: none;}
  .topnav a.icon {
    float: right;
    display: block;
  }
}
@media screen and (max-width: 225px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive a.icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
  }
}
.topnav {
  background-color:white;
  overflow: hidden;
}
.topnav a {
  float: left;
  color: blue;
  text-align: center;
  padding: 10px 10px;
  text-decoration: none;
  font-size: 17px;
}
.topnav a:hover {
  background-color: #ddd;
  color: blue;
}
.topnav a.active {
  background-color:darkblue;
  color:white;
}
.topnav .icon {
  display: none;
}
.active{
border-radius: 50%;
}
</style>
<body>
<header>
<div class="navigation-bar">
    <img src="ezcoin-logo1.png" class="logo">
    <div id="navigation-container">
      <ul>
        <li><a href="#">HOME</a></li>
        <li><a href="#">ABOUT</a></li>
        <li><a href="#">WHAT WE DO</a></li>
        <li><a href="#">CONTACT</a></li>
      </ul>
    </div>
</header>
<br>
<br>
<div class="form">
<form>
<div class="topnav" id="myTopnav">
  <ul>
    <li><a href="#Pix" class="active">Pix</a></li>
  <li><a href="profile.html">Profile</a></li>
<li>  <a href="invest.html">Invest</a></li>
  <li><a href="withraw.html" class="">Withraw</a></li>
  <a href="wallet.html">Wallet#000</a>
 <li> <a href="logout.html">Logout</a></li>
  </ul>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>
</label><br><br><br><br><br><br>
<label>MIDDLE NAME<input type="text" value=""placeholder="enter your middle name"><br><br><br><br><br><br>
<label>LAST NAME NAME<input type="text" value=""placeholder="enter your last name"><br><br><br><br><br><br>
<label>EMAIL <input type="email" value=""placeholder="Enter email"></label><br><br><br><br><br><br>
<label>PASSWORD  <input type="password" value=""placeholder="Password"></label><br><br><br><br><br><br>
</form>
</div>                       
<footer>
<h2>Don't miss out, get your EZ Wallet now.</h2>
<div>  
Copyright © 2022 EZ Coin. All Rights Reserved.   
</div>  
</footer>
</body>
</html>